apiVersion: v1
kind: Service
metadata:
  name: usuario-cliente-app-nodeport-svc
spec:
  type: NodePort
  selector:
    app: usuario-cliente-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31201

---

apiVersion: v1
kind: Service
metadata:
  name: usuario-cliente-app-loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: usuario-cliente-app 
  ports:
    - port: 3000
      targetPort: 3000
