name: Unit Tests
permissions:
  checks: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Check
    uses: postech-5soat-grupo-25/tech-challenge-templates/.github/workflows/unit-tests.yml@main
